name: Demo WebApp

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  AZURE_WEBAPP: '.'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore
      
    - name: dotnet publish
      run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP }}/output

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: output/
